## Carga inicial de los datos

Cargamos con pandas en memoria nuestro dataset de libros

In [103]:
import pandas as pd

df = pd.read_csv("books.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3080 entries, 0 to 3079
Data columns (total 37 columns):
id                           3080 non-null int64
isbn                         3051 non-null object
author                       0 non-null float64
title                        3080 non-null object
isbn13                       3061 non-null float64
asin                         2 non-null object
kindle_asin                  0 non-null float64
marketplace_id               0 non-null float64
country_code                 3080 non-null object
publication_date             3080 non-null object
publisher                    3038 non-null object
language_code                1208 non-null object
is_ebook                     3080 non-null bool
books_count                  3080 non-null int64
best_book_id                 3080 non-null int64
reviews_count                3080 non-null int64
ratings_sum                  3080 non-null int64
ratings_count                3080 non-null int64
text_revi

In [104]:
df.head()

id        isbn  author                                              title  \
0   1  0439785960     NaN  Harry Potter and the Half-Blood Prince (Harry ...   
1   3  0439554934     NaN  Harry Potter and the Sorcerer's Stone (Harry P...   
2   5  043965548X     NaN  Harry Potter and the Prisoner of Azkaban (Harr...   
3   7  0439887453     NaN   The Harry Potter Collection (Harry Potter, #1-6)   
4   9  0976540606     NaN  Unauthorized Harry Potter Book Seven News: "Ha...   

         isbn13 asin  kindle_asin  marketplace_id country_code  \
0  9.780440e+12  NaN          NaN             NaN           ES   
1  9.780440e+12  NaN          NaN             NaN           ES   
2  9.780440e+12  NaN          NaN             NaN           ES   
3  9.780440e+12  NaN          NaN             NaN           ES   
4  9.780977e+12  NaN          NaN             NaN           ES   

  publication_date        ...        average_rating num_pages  \
0        2006/9/16        ...                  4.56     652.0   
1        1997/6/26        ...                  4.46     320.0   
2         2004/5/1        ...                  4.55     435.0   
3         2006/9/1        ...                  4.73       NaN   
4        2005/4/26        ...                  3.69     152.0   

                  format  edition_information  ratings_count_global  \
0              Paperback                  NaN               1919694   
1              Hardcover                  NaN               5536122   
2  Mass Market Paperback                  NaN               2120869   
3              Paperback              Box Set                  1597   
4              Paperback                  NaN                    18   

   text_reviews_count_global                            authors   to_read  \
0                      25791  ['J.K. Rowling', 'Mary GrandPré']  229495.0   
1                      69174  ['J.K. Rowling', 'Mary GrandPré']    3286.0   
2                      33324  ['J.K. Rowling', 'Mary GrandPré']  193024.0   
3                        115  ['J.K. Rowling', 'Mary GrandPré']    4521.0   
4                          1         ['W. Frederick Zimmerman']      27.0   

    read currently_reading  
0   7492           22335.0  
1  15019           87801.0  
2  10469           31945.0  
3     24             189.0  
4      2               NaN  

[5 rows x 37 columns]

### average_rating
Analizamos la columna "average_rating". En caso de tener valores, deberemos filtrar los registros que correspondan en una vista para hacer calculos. P.ej calcular los libros que tengan valoración por encima de la media

In [105]:
df.average_rating = df.average_rating.fillna(value="unknow")
df.average_rating.value_counts()

4.00    137
0.00     81
4.06     51
3.67     50
3.75     46
4.11     45
3.83     43
5.00     43
4.25     42
3.96     42
3.00     41
3.50     40
4.14     40
4.05     39
4.13     39
3.92     38
4.04     38
3.88     37
3.90     37
3.94     37
3.71     36
3.79     36
3.95     36
4.12     35
3.82     34
3.86     33
4.03     33
4.22     32
4.33     32
4.20     32
       ... 
4.54      2
3.36      2
4.87      1
2.76      1
4.69      1
2.92      1
4.77      1
1.50      1
2.88      1
2.79      1
4.79      1
2.77      1
3.16      1
3.19      1
2.80      1
4.61      1
4.82      1
3.07      1
3.06      1
2.95      1
2.78      1
4.68      1
3.15      1
4.74      1
3.13      1
2.66      1
4.78      1
4.88      1
3.35      1
2.96      1
Name: average_rating, Length: 193, dtype: int64

### num_pages
Analizamos la columna "num_pages". Observamos que hay valores nulos. Tenemos que tenerlo en cuenta a la hora de calcular datos con ésta columna (p.ej la media, etc).

In [106]:
df.num_pages.isna().sum()

203

Comprobamos que si hay libros con 0 páginas. En ese caso cambiamos su valor por np.nan

In [107]:
import numpy as np
df.loc[df.num_pages == 0, "num_pages"] = np.nan
df.num_pages.isna().sum()

231

In [108]:
df.num_pages.loc[~df.num_pages.isna()].mean() #num_pages_mean sin tener en cuenta datos nulos

303.5328185328185

In [129]:
df.num_pages.loc[~df.num_pages.isna()].astype("int64").unique()

array([ 652,  320,  435,  152,  815,  544, 1184, 1216,  558,   48,  144,
        228,  304,  137,  339,  334,  248,  208,  138,  192,  298,  123,
        240,  423,  592,  480,  471,  256,  386,  260,  384,  391,  873,
        514,  368,  308,  216,   32,  352,  738,   24,  217,  288,  244,
        314,  246,  178,  311,  245,  272,   80,  559,  224,  176,  589,
        439,  232,  336,  342, 1085,  776,  199,   40,  104,  608,  262,
         88,  128,  828,  397,  328,  287,  432,  186,  103,  341,  255,
        296,  520,  319,  392,  112,  200,  448,  160,  222,  127,  571,
        416,  456,  226,  212,   16,    8,  496,  363,  927,  381,   84,
         79,  292,  134,  221,   58,  400,  202,  235,  196,  157,  467,
        206,  383,  258,  197,  231,  273,  166,  285,  399, 1344,  405,
        291,  250,   64,   68,  102,  191,  181,  542,  367,  506,  464,
        512,  125,  340,  472,  161,  366,  129,  172,  164,  190,  300,
         90,  126,  519,  555,  672,   95,  624,  3

### format
Analizamos la columna "format" y observamos valores nulos

In [110]:
df.format.unique()

array(['Paperback', 'Hardcover', 'Mass Market Paperback', 'Audio CD', nan,
       'Unknown Binding', 'Spiral-bound', 'Library Binding',
       'Kindle Edition', 'hardback', 'Leather Bound', 'Spiral Bound',
       'Audiobook', 'Hardcover - Deluxe Illustrated Edition', 'cloth',
       'Board Book', 'Audio Cassette', 'ebook', 'MP3 CD', 'Audio',
       'Novelty Book', 'Rag Book', 'CD-ROM', 'コミック', 'Loose-Leaf'],
      dtype=object)

Para evitar el borrado de muchos libros de forma inncesaria, todos los libros en los que no tengamos un formato especificado, le asignamos el formato "unknow"

In [111]:
df.format = df.format.fillna(value="unknow")
df.format.value_counts()

Paperback                                 1992
Hardcover                                  823
Audio CD                                    69
Mass Market Paperback                       69
unknow                                      58
Unknown Binding                             20
Audiobook                                    7
Spiral-bound                                 7
Audio Cassette                               6
Board Book                                   5
Library Binding                              4
Kindle Edition                               2
コミック                                         2
hardback                                     2
Audio                                        2
cloth                                        2
ebook                                        2
Loose-Leaf                                   1
Novelty Book                                 1
CD-ROM                                       1
Spiral Bound                                 1
Hardcover - D

### edition_information
Analizamos la columna "edition_information" y observamos valores nulos. 

In [112]:
df.edition_information.unique()

array([nan, 'Box Set', 'Dramatization edition; unabridged',
       'First Trade Paperback Edition', '50th Anniversary Edition',
       '50th Anniversary One-volume Edition', '1st edition',
       'High Risk Books Series', 'Reissue edition',
       'Series: Golden Kite Honors', 'Second Edition', '1st Edition',
       'First Edition Edition', 'Unabridged', 'First Paperback Edition',
       'Abridged', 'Penguin Classics Deluxe Edition',
       'Harlequin Blaze #264', '1st Scribner trade paperback edition',
       '3rd Edition', 'First Vintage International Edition (US/CAN)',
       'Fourth Edition', 'P.S. Edition (US/CAN)', 'New Edition',
       'Special Illustrated Edition; First Paperback Edition (US/CAN)',
       'Large Print', 'US / Canada', 'P.S. (USA/CAN)', 'UK Edition',
       'Revised and Expanded Edition, Unabridged', 'Sixth Edition',
       'Oxford World’s Classics', 'Modern Library Classics, USA / CAN',
       'Movie Tie-In Edition', "The Illustrated Children's Library",
      

Para evitar el borrado de muchos libros de forma inncesaria, todos los libros en los que no tengamos un formato especificado, le asignamos el formato "unknow". Podemos observar que en la mayoría de los casos no se ha propocionado información por lo que esta información puede terminar no siendo de utilidad. 

In [113]:
df.edition_information = df.edition_information.fillna(value="unknow")
df.edition_information.value_counts()

unknow                                                           2856
Abridged                                                           22
Second Edition                                                     15
Large Print                                                        12
First Edition                                                      12
1st edition                                                         6
Penguin Classics                                                    6
Unabridged                                                          5
1st Edition                                                         3
Norton Critical Edition                                             3
Sixth Edition                                                       3
Oxford World's Classics                                             3
Box Set                                                             3
Third Edition                                                       2
50th Anniversary Edi

### ratings_count_global
Analizamos ahora "ratings_count_global". Representa el total de valoraciones que ha recibido el libro.
En caso de tener algun valor nulo, lo reemplazamos por cero.

Como tiene muchos valores "unique" distintos, podemos comprobar que no tiene valores nulos con: 

In [114]:
df.ratings_count_global = df.ratings_count_global.fillna(value=0)
df.ratings_count_global.isna().sum()

0

Además, el tipo de datos es el correcto para un contador

In [115]:
df.ratings_count_global.dtype

dtype('int64')

### text_reviews_count_global
Analizamos la columna "text_reviews_count_global". Representa el número de personas que han escrito una review del libro. Reemplazamos los valores nulos por 0 y comprobamos que no tengamos valores nulos

In [116]:
df.text_reviews_count_global = df.text_reviews_count_global.fillna(value=0)
df.text_reviews_count_global.isna().sum()

0

### to_read
Analizamos la columna "to_read". Representa el número de personas que quieren leer el libro. Reemplazamos los valores nulos por 0 y comprobamos que no tengamos valores nulos

In [117]:
df.to_read = df.to_read.fillna(value=0)
df.to_read.isna().sum()

0

Dado que representa un número de personas, expresamos los resultados como números enteros

In [131]:
df.to_read.astype("int64")

0       229495
1         3286
2       193024
3         4521
4           27
5        93424
6        34566
7       241899
8       153158
9       153158
10      153158
11         883
12          14
13        1497
14          68
15         182
16        6770
17         444
18        2353
19         988
20         810
21         155
22          28
23         948
24          84
25         104
26          37
27       15686
28         761
29       15720
         ...  
3050      2038
3051         5
3052        27
3053       291
3054         7
3055         1
3056         7
3057       443
3058        20
3059       178
3060        64
3061      4394
3062        49
3063     32887
3064      9577
3065      7806
3066     11830
3067     11830
3068      2911
3069       407
3070       334
3071       234
3072       206
3073       229
3074      5740
3075      5433
3076       986
3077       584
3078       636
3079       311
Name: to_read, Length: 3080, dtype: int64

### read
Analizamos la columna "read". Representa el número de personas que han leído el libro. Reemplazamos los valores nulos por 0 y comprobamos que no tengamos valores nulos

In [119]:
df.read = df.read.fillna(value=0)
df.read.isna().sum()

0

Se puede observar igualmente que ésta columna tiene bien el tipo de dato para lo que queremos representar

In [120]:
df.read.dtype

dtype('int64')

### currently_reading
Analizamos la columna "currently_reading". Representa el número de personas que están leyendo el libro. Podemos ver que tiene valores nulos.

In [121]:
df.currently_reading.isna().sum()

709

Procedemos a sustituir esos nulos por el valor "cero" como en el caso anterior de la columna "to_read"

In [122]:
df.currently_reading = df.currently_reading.fillna(value=0)
df.currently_reading.isna().sum()

0

Podemos ver que es necesario ajustar esta columna para que se represente como valores enteros en lugar de float

In [133]:
df.currently_reading.unique()[:15]

array([2.2335e+04, 8.7801e+04, 3.1945e+04, 1.8900e+02, 0.0000e+00,
       1.1483e+04, 1.0440e+03, 1.6677e+04, 2.0281e+04, 1.7600e+02,
       1.0200e+02, 3.0000e+00, 3.2000e+01, 1.8000e+01, 9.7000e+01])

In [132]:
df.currently_reading.astype("int64").unique()[:15]

array([22335, 87801, 31945,   189,     0, 11483,  1044, 16677, 20281,
         176,   102,     3,    32,    18,    97])